source "https://cdn.cocoapods.org/"

target 'MQTTClientTests' do
	platform :ios, '14.0'
	pod 'CocoaLumberjack', '3.7.4'
	pod 'MQTTClient/MinL', :path => '..'
	pod 'MQTTClient/ManagerL', :path => '..'
	pod 'MQTTClient/WebsocketL', :path => '..'
  pod 'SocketRocket', '0.5.1'
end

target 'MQTTClientTVTests' do
	platform :tvos, '9.0'
	pod 'CocoaLumberjack', '3.7.4'
	pod 'MQTTClient/MinL', :path => '..'
	pod 'MQTTClient/ManagerL', :path => '..'
	pod 'MQTTClient/WebsocketL', :path => '..'
  	pod 'SocketRocket', '0.5.1'
end

target 'MQTTClientOSXTests' do
	platform :osx, '10.10'
	pod 'CocoaLumberjack', '3.7.4'
	pod 'MQTTClient/MinL', :path => '..'
	pod 'MQTTClient/ManagerL', :path => '..'
	pod 'MQTTClient/WebsocketL', :path => '..'
  	pod 'SocketRocket', '0.5.1'
end
